### ISSUE TITLE
淘宝接口又有变更，这个项目会继续吗？

### ISSUE THREAD

**Issue by huang-sheng** [shjia/taobao_spider#2]
淘宝接口又有变更，这个项目会继续吗？可以一起讨论下。

**Comment by huang-sheng** [comment]
https://hws.alicdn.com/cache/wdetail/5.0/?callback=&id=2402599005&exParams=%7B%7D&_=1505809608796
这个接口已经下线了，目前需要从手机端想办法解决，移动端接口如下： https://h5api.m.taobao.com/h5/mtop.taobao.detail.getdetail/6.0/?jsv=2.4.11&appKey=12574478&t=1534321788422&sign=394dbd38f9fb4234abf6a377192be580&api=mtop.taobao.detail.getdetail&v=6.0&ttid=2018%40taobao_iphone_9.9.9&utdid=123123123123123&isSec=0&ecode=0&AntiFlood=true&AntiCreep=true&H5Request=true&type=jsonp&dataType=jsonp&callback=mtopjsonp1&data=%7B%22itemNumId%22%3A%22568935661158%22%2C%22exParams%22%3A%22%7B%5C%22spm%5C%22%3A%5C%22a219r.lm5734.14.17.7a3a7e23faR4ll%5C%22%2C%5C%22id%5C%22%3A%5C%22568935661158%5C%22%2C%5C%22ns%5C%22%3A%5C%221%5C%22%2C%5C%22abbucket%5C%22%3A%5C%2214%5C%22%7D%22%2C%22detail_v%22%3A%223.1.1%22%2C%22ttid%22%3A%222018%40taobao_iphone_9.9.9%22%2C%22utdid%22%3A%22123123123123123%22%7D 
希望能一起探讨。

**Comment by shjia** [comment]
> 淘宝接口又有变更，这个项目会继续吗？可以一起讨论下。

可以参考下 Model/Taobao.php 的GetDetail部分 @huang-sheng

**Comment by 3394772548** [comment]
https://github.com/3394772548/yue-spider
